### ISSUE TITLE
Search bar needs to center the text

### ISSUE THREAD

**Issue by huayunh** [pxblue/doc-it#195]
#### Describe the desired behavior
It wasn't completely uncomfortable until we tried it out on Safari. There is a padding on the text field component that shifts the text off-center a little bit. 

#### Describe the current behavior
in chrome
![image](https://user-images.githubusercontent.com/8997218/83782725-ed340480-a65d-11ea-9e94-91158813f431.png)

in safari
![image](https://user-images.githubusercontent.com/8997218/83782476-d9889e00-a65d-11ea-879a-368194a00077.png)

**Comment by emclaug2** [comment]
I'm thinking this issue was already addressed on a previous PR and just wasn't closed.  I'm attaching some gifs to verify.   Should this issue still open @huayunh ?

With text entered: 
![Drawer Text Centered](https://user-images.githubusercontent.com/6538289/89783180-80693a80-dae4-11ea-92a8-16b637e2c9c9.gif)

With cursor: 
![Drawer Text Centered2](https://user-images.githubusercontent.com/6538289/89783258-a4c51700-dae4-11ea-9ac5-3102949e60c8.gif)

**Comment by emclaug2** [comment]
I just checked on Safari, the issue is fixed on Chrome but not Safari.
